apiVersion: v1
data:
  password: e5c6b6de-92f7-42cd-b7ca-404b73aebc6a
  username: vistasunil
kind: Secret
metadata:
  annotations:
    tekton.dev/docker-0: registry.hub.docker.com/vistasunil
  name: ibm-registry-secret
  namespace: default
type: kubernetes.io/basic-auth
